
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: product_development

test:
  <<: *default
  database: product_test

production:
  primary: &primary_production
    <<: *default
    database: product_production
    username: product
    password: <%= ENV["PRODUCT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: product_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: product_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: product_production_cable
    migrations_paths: db/cable_migrate
